apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-container-app-mfso
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-container-app-mfso
    app.kubernetes.io/part-of: sca
  name: single-container-app-mfso
  namespace: user1-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: single-container-app-mfso
status:
  loadBalancer: {}
